name: Build and Deploy Streamlit App to Cloud Run

on:
  push:
    branches: [ "main" ] # main ブランチへの push でトリガー

env:
  PROJECT_ID: your-project-id # <<< 要変更: あなたのGCPプロジェクトID
  REGION: asia-northeast1 # <<< 要変更: デプロイするリージョン
  SERVICE_NAME: your-chat-app-name # <<< 要変更: Cloud Run サービス名
  ARTIFACT_REGISTRY: your-artifact-registry-repo # <<< 要変更: Artifact Registry リポジトリ名
  GAR_LOCATION: asia-northeast1 # <<< 要変更: Artifact Registry のリージョン
  # Cloud Run に割り当てるサービスアカウント
  APP_SA_EMAIL: your-app-service-account@your-project-id.iam.gserviceaccount.com # <<< 要変更
  # Cloud Functions の HTTPS Trigger URL
  CHAT_API_FUNCTION_URL: https://your-function-url.a.run.app # <<< 要変更: デプロイ後に取得
  # (オプション) 事前承認済みユーザーリストなど
  # PREAUTHORIZED_EMAILS: "user1@example.com,user2@example.com"
  # ALLOWED_CHAT_PARTNERS: "user1@example.com,user2@example.com"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Workload Identity Federation に必要

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud (Workload Identity Federation)
      id: auth
      uses: google-github-actions/auth@v2
      with:
        # !!! 重要: この値はあなたの GCP WIF 設定に合わせて手動で変更してください !!!
        workload_identity_provider: 'projects/YOUR_PROJECT_NUMBER/locations/global/workloadIdentityPools/your-pool-id/providers/your-provider-id'
        # デプロイ操作を行うサービスアカウント (Deploy SA)
        service_account: your-deploy-sa@your-project-id.iam.gserviceaccount.com # <<< 要変更

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Dockerfile がルートにあるためコンテキストは .
        push: true
        tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        # ビルドしたイメージを指定
        image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        # サービスアカウントをCloud Runサービスに割り当て
        service_account: ${{ env.APP_SA_EMAIL }}
        # Secret Manager から OAuth 情報と Cookie 情報を環境変数としてマウント
        secrets: |-
          GOOGLE_CLIENT_ID=google-client-id:latest
          GOOGLE_CLIENT_SECRET=google-client-secret:latest
          COOKIE_KEY=cookie-key:latest
          COOKIE_NAME=cookie-name:latest
        # 環境変数を設定 (Function URL など)
        env_vars: |-
          CHAT_API_FUNCTION_URL=${{ env.CHAT_API_FUNCTION_URL }}
          # 必要に応じて他の環境変数も設定
          # PREAUTHORIZED_EMAILS=${{ env.PREAUTHORIZED_EMAILS }}
          # ALLOWED_CHAT_PARTNERS=${{ env.ALLOWED_CHAT_PARTNERS }}
        # 必要に応じて他の Cloud Run 設定を追加
        # memory: "512Mi"
        # cpu: "1"
        # concurrency: 80

    - name: Show Cloud Run Service URL
      run: echo "Cloud Run Service URL: ${{ steps.deploy.outputs.url }}"
